
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package DanielC_EXA_U6;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int P_TRUE = 42;
  public static final int P_INT = 8;
  public static final int P_THROWS = 80;
  public static final int OPR_MAY = 30;
  public static final int P_LONG = 9;
  public static final int P_WHILE = 51;
  public static final int CMD = 69;
  public static final int P_CHAR = 12;
  public static final int OP_MUL = 19;
  public static final int P_IMPORT = 76;
  public static final int OPR_DIF = 29;
  public static final int OP_MOD = 21;
  public static final int P_VOID = 15;
  public static final int P_BREAK = 53;
  public static final int P_ELSE = 55;
  public static final int P_PACKAGE = 77;
  public static final int P_PROTECTED = 4;
  public static final int OPR_IG = 28;
  public static final int P_NULL = 41;
  public static final int OPR_MENIG = 33;
  public static final int OPL_ANDSIMP = 36;
  public static final int OPU_DEC = 39;
  public static final int AG_LLC = 47;
  public static final int AG_LLA = 46;
  public static final int OP_MODASIG = 27;
  public static final int OP_DIV = 20;
  public static final int AG_PC = 45;
  public static final int AG_PA = 44;
  public static final int P_NEW = 78;
  public static final int P_EXTENDS = 73;
  public static final int P_STRING = 16;
  public static final int P_BOOLEAN = 13;
  public static final int P_STATIC = 72;
  public static final int P_ABSTRACT = 71;
  public static final int OP_SUMASIG = 23;
  public static final int COMENT = 82;
  public static final int OP_ASIG = 22;
  public static final int AG_CC = 49;
  public static final int AG_CA = 48;
  public static final int P_CASE = 58;
  public static final int OPR_MEN = 31;
  public static final int DPT = 64;
  public static final int P_BYTE = 6;
  public static final int OP_RES = 18;
  public static final int OPL_AND = 34;
  public static final int P_DOUBLE = 11;
  public static final int DP = 67;
  public static final int P_SHORT = 7;
  public static final int OP_DIVASIG = 25;
  public static final int P_DEFAULT = 5;
  public static final int P_FINALLY = 61;
  public static final int OPU_INC = 38;
  public static final int P_ELSEIF = 56;
  public static final int VS = 87;
  public static final int P_CONST = 14;
  public static final int P_IMPLEMENTS = 74;
  public static final int VN = 84;
  public static final int OPL_ORSIMP = 37;
  public static final int EOF = 0;
  public static final int P_DO = 50;
  public static final int VD = 85;
  public static final int VC = 86;
  public static final int OP_MULASIG = 26;
  public static final int P_CONTINUE = 62;
  public static final int P_CATCH = 60;
  public static final int CM = 66;
  public static final int OPR_MAYIG = 32;
  public static final int error = 1;
  public static final int CE = 68;
  public static final int ID = 83;
  public static final int P_FALSE = 43;
  public static final int P_FINAL = 79;
  public static final int P_FLOAT = 10;
  public static final int OPU_NEG = 40;
  public static final int P_PRIVATE = 3;
  public static final int OP_SUM = 17;
  public static final int P_IF = 54;
  public static final int UPT = 63;
  public static final int TPT = 65;
  public static final int P_CLASS = 75;
  public static final int P_SWITCH = 57;
  public static final int P_FOR = 52;
  public static final int CMS = 70;
  public static final int OPL_OR = 35;
  public static final int P_RETURN = 81;
  public static final int P_PUBLIC = 2;
  public static final int OP_RESASIG = 24;
  public static final int P_TRY = 59;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "P_PUBLIC",
  "P_PRIVATE",
  "P_PROTECTED",
  "P_DEFAULT",
  "P_BYTE",
  "P_SHORT",
  "P_INT",
  "P_LONG",
  "P_FLOAT",
  "P_DOUBLE",
  "P_CHAR",
  "P_BOOLEAN",
  "P_CONST",
  "P_VOID",
  "P_STRING",
  "OP_SUM",
  "OP_RES",
  "OP_MUL",
  "OP_DIV",
  "OP_MOD",
  "OP_ASIG",
  "OP_SUMASIG",
  "OP_RESASIG",
  "OP_DIVASIG",
  "OP_MULASIG",
  "OP_MODASIG",
  "OPR_IG",
  "OPR_DIF",
  "OPR_MAY",
  "OPR_MEN",
  "OPR_MAYIG",
  "OPR_MENIG",
  "OPL_AND",
  "OPL_OR",
  "OPL_ANDSIMP",
  "OPL_ORSIMP",
  "OPU_INC",
  "OPU_DEC",
  "OPU_NEG",
  "P_NULL",
  "P_TRUE",
  "P_FALSE",
  "AG_PA",
  "AG_PC",
  "AG_LLA",
  "AG_LLC",
  "AG_CA",
  "AG_CC",
  "P_DO",
  "P_WHILE",
  "P_FOR",
  "P_BREAK",
  "P_IF",
  "P_ELSE",
  "P_ELSEIF",
  "P_SWITCH",
  "P_CASE",
  "P_TRY",
  "P_CATCH",
  "P_FINALLY",
  "P_CONTINUE",
  "UPT",
  "DPT",
  "TPT",
  "CM",
  "DP",
  "CE",
  "CMD",
  "CMS",
  "P_ABSTRACT",
  "P_STATIC",
  "P_EXTENDS",
  "P_IMPLEMENTS",
  "P_CLASS",
  "P_IMPORT",
  "P_PACKAGE",
  "P_NEW",
  "P_FINAL",
  "P_THROWS",
  "P_RETURN",
  "COMENT",
  "ID",
  "VN",
  "VD",
  "VC",
  "VS"
  };
}

